#!/bin/bash

topdir=$(git rev-parse --show-toplevel)

find ${topdir} -type f -name ".terraform.lock.hcl" -ls -delete
find ${topdir} -type f -name "terraform.tfstate" -ls -delete
find ${topdir} -type f -name "terraform.tfstate.backup" -ls -delete
find ${topdir} -type d -name ".terraform" -ls -exec rm -rf {} \;
